# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nenecare
spring.datasource.username=postgres
spring.datasource.password=passer
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Nom de l'application
spring.application.name=nenecare

# Port du serveur
server.port=8081

# JWT
jwt.secret=nenecare-secret-key-clinique-marose-ouakam-2026
jwt.expiration=1800000